### ISSUE TITLE
AM/PM suffix for 12-hour format

### ISSUE THREAD

**Issue by arvislacis** [tong/atom-clock#8]
I think that it would be nice if user checks out 24-hour format (selects to use 12 hour format) then clock shows extra suffixes - AM and PM to current time. Anyway, this is just idea because I am European.
![screenshot from 2015-10-17 01 29 09](https://cloud.githubusercontent.com/assets/626982/10554774/524fb056-746f-11e5-9044-f29d54cd534e.png)

**Comment by tong** [comment]
Sounds legit

**Comment by tong** [comment]
Added with 94ca32b. Will be available on next release.
